### ISSUE TITLE
Module is not asyncronous

### ISSUE THREAD

**Issue by jacobtomlinson** [anxodio/database-sqlite#2]
This module is using the standard `sqlite3` module which is blocking. Operations like `execute()` will block the thread until they are done. 

As opsdroid uses asyncio then all io operations like database commands should be asynchronous. 

I recommend looking at [aiosqlite](https://github.com/jreese/aiosqlite) which provides an async wrapper for the standard `sqlite3` module. This allows `execute()` commands to be called with `await` which frees up the loop to do other things while the database operation happens.

**Comment by anxodio** [comment]
Totally agree, I will try it. I started with aioodbc but it was a mess of dependencies and I decided to just use sqlite, but I didn't search for something with aio and sqlite. Thanks!
