### ISSUE TITLE
`file` is a protected word

### ISSUE THREAD

**Issue by jacobtomlinson** [anxodio/database-sqlite#4]
I see you've created a variable called `file` [here](https://github.com/anxodio/database-sqlite/blob/master/sqlite.py#L21).

In python `file` is a [constructor method](https://docs.python.org/2/library/functions.html#file) for creating new file objects. Overriding it as a variable could cause problems.

This should be renamed.

**Comment by anxodio** [comment]
Using a reserved name again. I am a bad boy xD
